--1.
SELECT COUNT(coda)
 FROM ATOR
 WHERE sexo='f';

--2.
SELECT nomeart, COUNT(ATOR.coda) 
FROM ATOR, PERSONAGEM 
WHERE ATOR.coda=PERSONAGEM.coda GROUP BY PERSONAGEM.coda

--3.
 SELECT nomeart, MIN (FILME.ano) 
FROM ATOR, FILME, PERSONAGEM
 WHERE ATOR.oscar=0 and ATOR.coda = PERSONAGEM.coda and FILME.codf= PERSONAGEM.codf GROUP BY ATOR.coda;

--4.
SELECT nome, COUNT (personagem) 
FROM FILME, PERSONAGEM 
WHERE FILME.codf = PERSONAGEM.codf GROUP BY PERSONAGEM.codf

--5.
SELECT ano, COUNT (codf)
 FROM FILME GROUP BY FILME.ano

--6.
SELECT nomeart 
FROM ATOR, PERSONAGEM 
WHERE ATOR.coda = PERSONAGEM.coda AND PERSONAGEM.cache > ( SELECT AVG(cache) FROM PERSONAGEM) GROUP BY ATOR.coda;

--7.
SELECT nomeart, COUNT(*) 
FROM ATOR, PERSONAGEM
WHERE ATOR.coda = PERSONAGEM.coda GROUP BY nomeart HAVING COUNT(*)>=2

